/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isdrozklad;


import java.io.*;

public class App {

    public static void main(String[] args) throws IOException {
        ScheduleParser scheduleParser = new ScheduleParser("C:\\Users\\Ineed\\Downloads\\group-time-table.xls");
//        scheduleParser.getNextWeekSchedule();
        System.out.println(MyDateUtils.getDayAfter());
    }
}
